apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-solr
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOON_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
  - name: DEPLOYMENT_STRATEGY
    description: Strategy of Deploymentconfig
    value: "Recreate"
  - name: SERVICE_IMAGE
    description: Pullable image of service
    required: true
  - name: CRONJOBS
    description: Oneliner of Cronjobs
    value: ""
  - name: PERSISTENT_STORAGE_SIZE
    description: Size of the Storage to request
    value: "1Gi"
  - name: ENVIRONMENT_TYPE
    description: production level of this environment
    value: 'production'
  - name: CONFIG_MAP_SHA
    description: SHA sum of the configmap
    value: ''
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      service: ${SERVICE_NAME}
    strategy:
      type: ${DEPLOYMENT_STRATEGY}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          project: ${SAFE_PROJECT}
        annotations:
          appuio.ch/backupCommand: /bin/sh -c "/bin/busybox tar -cf - -C /var/solr ."
          backup.appuio.ch/fileExtension: .${SERVICE_NAME}.tar
          lagoon.sh/configMapSha: ${CONFIG_MAP_SHA}
      spec:
        volumes:
          - name: ${SERVICE_NAME}
            persistentVolumeClaim:
              claimName: ${SERVICE_NAME}
        priorityClassName: lagoon-priority-${ENVIRONMENT_TYPE}
        containers:
        - image: ${SERVICE_IMAGE}
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 8149
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /solr
              port: 8983
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /solr
              port: 8983
            initialDelaySeconds: 90
            timeoutSeconds: 3
            failureThreshold: 5
          envFrom:
          - configMapRef:
              name: lagoon-env
          env:
          - name: SERVICE_NAME
            value: ${SERVICE_NAME}
          - name: CRONJOBS
            value: ${CRONJOBS}
          volumeMounts:
            - name: ${SERVICE_NAME}
              mountPath: /var/solr
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
    test: false
    triggers:
    - type: ConfigChange
