controller:
  service:
    type: NodePort
    nodePorts:
      http: "32080"
      https: "32443"
  config:
    proxy-body-size: 100m
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true