apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-configmap
parameters:
  - name: NAME
    description: Name of this configmap
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: OPENSHIFT_NAME
    description: The name of the openshift cluster this project is running on
    value: ""
  - name: ENVIRONMENT_TYPE
    description: Which environment type this project is
  - name: ROUTE
    description: The main route of this project
    value: ""
  - name: ROUTES
    description: All routes of this project
    value: ""
  - name: ACTIVE_ROUTES
    description: All active routes of this project if it is the active production environment
    value: ""
  - name: STANDBY_ROUTES
    description: All standby routes of this project if it is the standby production environment
    value: ""
  - name: MONITORING_URLS
    description: The routes specified for monitoring the production environment of this project
    value: ""
  - name: AUTOGENERATED_ROUTES
    description: Routes which were automatically generated by Lagoon
    value: ""
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${NAME}
  data:
    LAGOON_GIT_SAFE_BRANCH: ${SAFE_BRANCH}
    LAGOON_GIT_BRANCH: ${BRANCH}
    LAGOON_SAFE_PROJECT: ${SAFE_PROJECT}
    LAGOON_PROJECT: ${PROJECT}
    LAGOON_ENVIRONMENT: ${SAFE_BRANCH}
    LAGOON_ENVIRONMENT_TYPE: ${ENVIRONMENT_TYPE}
    LAGOON_ROUTE: ${ROUTE}
    LAGOON_ROUTES: ${ROUTES}
    LAGOON_ACTIVE_ROUTES: ${ACTIVE_ROUTES}
    LAGOON_STANDBY_ROUTES: ${STANDBY_ROUTES}
    LAGOON_MONITORING_URLS: ${MONITORING_URLS}
    LAGOON_OPENSHIFT_NAME: ${OPENSHIFT_NAME}
    LAGOON_AUTOGENERATED_ROUTES: ${AUTOGENERATED_ROUTES}
