apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-route
parameters:
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOON_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this route is in
    required: true
  - name: ROUTE_DOMAIN
    description: URL of the Router for this route
    required: true
  - name: ROUTE_SERVICE
    description: Name of the Service that this route should forward to
    required: true
  - name: ROUTE_TLS_ACME
    description: Setting of kubernetes.io/tls-acme annotation
    required: true
  - name: ROUTE_INSECURE
    description: Setting of insecureEdgeTerminationPolicy
    required: true
  - name: ROUTE_HSTS
    description: Setting of HTTP Strict Transport Security policy
    required: true
  - name: ROUTE_MIGRATE
    description: Setting to determine if this route should be migratable for active/standby purposes
    required: true
  - name: MONITORING_ENABLED
    description: Default to monitoring disabled, only enabled on production routes
    value: "false"
  - name: MONITORING_INTERVAL
    description: Frequency of checks by monitoring
    value: ""
  - name: MONITOR_ALERTCONTACTS
    description: Alertcontacts to associate to this monitor
    value: ""
  - name: MONITORING_PATH
    description: Path for monitoring of this route
    value: ""
  - name: MONITORING_STATUSPAGEID
    description: Uptime Robot status page ID
    value: ""
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/disable_cookies: 'true'
      haproxy.router.openshift.io/hsts_header: '${ROUTE_HSTS}'
      kubernetes.io/tls-acme: '${ROUTE_TLS_ACME}'
      monitor.stakater.com/enabled: '${MONITORING_ENABLED}'
      uptimerobot.monitor.stakater.com/interval: '${MONITORING_INTERVAL}'
      uptimerobot.monitor.stakater.com/alert-contacts: '${MONITOR_ALERTCONTACTS}'
      monitor.stakater.com/overridePath: '${MONITORING_PATH}'
      uptimerobot.monitor.stakater.com/status-pages: '${MONITORING_STATUSPAGEID}'
    creationTimestamp: null
    labels:
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
      lagoon/autogenerated: "false"
      dioscuri.amazee.io/migrate: '${ROUTE_MIGRATE}'
    name: ${ROUTE_DOMAIN}
  spec:
    host: ${ROUTE_DOMAIN}
    port:
      targetPort: http
    to:
      kind: Service
      name: ${ROUTE_SERVICE}
    tls:
      insecureEdgeTerminationPolicy: ${ROUTE_INSECURE}
      termination: edge
