apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-prebackuppod
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SERVICE_NAME_UPPERCASE
    description: Name of this service in uppercase
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOON_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
  - name: DEPLOYMENT_STRATEGY
    description: Strategy of Deploymentconfig
    value: "Recreate"
  - name: SERVICE_IMAGE
    description: Pullable image of service
  - name: CRONJOBS
    description: Oneliner of Cronjobs
    value: ""
objects:
- apiVersion: backup.appuio.ch/v1alpha1
  kind: PreBackupPod
  metadata:
    name: ${SERVICE_NAME}-prebackuppod
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
  spec:
    backupCommand: >-
      /bin/sh -c "dump=$(mktemp)
      && mysqldump --max-allowed-packet=500M --events --routines --quick
      --add-locks --no-autocommit --single-transaction --no-create-db
      --no-data
      -h $BACKUP_DB_HOST
      -u $BACKUP_DB_USERNAME
      -p$BACKUP_DB_PASSWORD
      $BACKUP_DB_DATABASE
      > $dump
      && mysqldump --max-allowed-packet=500M --events --routines --quick
      --add-locks --no-autocommit --single-transaction --no-create-db
      --ignore-table=$BACKUP_DB_DATABASE.watchdog
      --no-create-info
      -h $BACKUP_DB_HOST
      -u $BACKUP_DB_USERNAME
      -p$BACKUP_DB_PASSWORD
      $BACKUP_DB_DATABASE
      >> $dump
      && cat $dump && rm $dump"
    fileExtension: .${SERVICE_NAME}.sql
    pod:
      metadata:
        labels:
          prebackuppod: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          project: ${SAFE_PROJECT}
          parent: ${SERVICE_NAME}
      spec:
        containers:
          - args:
              - sleep
              - infinity
            env:
              - name: BACKUP_DB_HOST
                valueFrom:
                  configMapKeyRef:
                    key: ${SERVICE_NAME_UPPERCASE}_HOST
                    name: lagoon-env
              - name: BACKUP_DB_USERNAME
                valueFrom:
                  configMapKeyRef:
                    key: ${SERVICE_NAME_UPPERCASE}_USERNAME
                    name: lagoon-env
              - name: BACKUP_DB_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    key: ${SERVICE_NAME_UPPERCASE}_PASSWORD
                    name: lagoon-env
              - name: BACKUP_DB_DATABASE
                valueFrom:
                  configMapKeyRef:
                    key: ${SERVICE_NAME_UPPERCASE}_DATABASE
                    name: lagoon-env
            image: imagecache.amazeeio.cloud/amazeeio/alpine-mysql-client
            imagePullPolicy: Always
            name: ${SERVICE_NAME}-prebackuppod
