name: Lagoon test

on:
  push:
    branches:
      - helm_actions
      - helm_actions_122
  pull_request:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        kindest_node_version: [v1.22.0]
        experimental: [false]
        # include:
        #   - kindest_node_version: v1.22.0
        #     experimental: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    # - name: Setup correct Go version
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: '1.16'
    # - name: Run Kubernetes tools
    #   uses: stefanprodan/kube-tools@v1
    - name: Get Kind IP
      run: |
        docker network create kind || true && docker run --rm --network kind alpine ip -o addr show eth0 | sed -nE 's/.* ([0-9.]{7,})\/.*/\1/p'
        echo "kind_ip=$(docker network create kind || true && docker run --rm --network kind alpine ip -o addr show eth0 | sed -nE 's/.* ([0-9.]{7,})\/.*/\1/p')" >> $GITHUB_ENV
        echo "Kind cluster is at ${{ env.kind_ip }}"
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "192.168.224.2"
        replace: ${{ env.kind_ip }}
        include: "helmvalues/*.yaml"
    - name: Check config
      run: |
        cat helmvalues/kind-config.yaml
    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        config: helmvalues/kind-config.yaml
        node_image: kindest/node:${{ matrix.kindest_node_version }}
        wait: 120s
    - name: Configure Helm repositories
      run: |
        helm plugin install https://github.com/aslafy-z/helm-git
        helm repo add harbor https://helm.goharbor.io
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo add stable https://charts.helm.sh/stable
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add minio https://helm.min.io/
        helm repo add amazeeio https://amazeeio.github.io/charts/
        helm repo add lagoon https://uselagoon.github.io/lagoon-charts/
        helm repo add lagoon-core-k8s-122 git+https://github.com/uselagoon/lagoon-charts@charts/lagoon-core?ref=k8s_122
        helm repo add lagoon-remote-k8s-122 git+https://github.com/uselagoon/lagoon-charts@charts/lagoon-remote?ref=k8s_122
        helm repo add lagoon-build-deploy-k8s-122 git+https://github.com/uselagoon/lagoon-charts@charts/lagoon-build-deploy?ref=k8s_122
        helm repo update
    - name: Install cluster pre-requisites
      run: |
        helm upgrade --install --create-namespace --namespace ingress-nginx --wait --timeout 30m --version 4.0.16 ingress-nginx ingress-nginx/ingress-nginx -f helmvalues/ingress-nginx.yaml
        helm upgrade --install --create-namespace --namespace registry --wait --timeout 30m --version 1.5.6 registry harbor/harbor -f helmvalues/registry.yaml
        helm upgrade --install --create-namespace --namespace nfs-server-provisioner --wait --timeout 30m --version 1.1.3 nfs-server-provisioner stable/nfs-server-provisioner -f helmvalues/nfs-server-provisioner.yaml
        helm upgrade --install --create-namespace --namespace minio --wait --timeout 30m --version 8.1.11 minio bitnami/minio -f helmvalues/minio.yaml
    # - name: Install DBaaS pre-requisites
    #   run: |
    #     helm upgrade --install --create-namespace --namespace mariadb --wait --timeout 30m --version=10.1.1 mariadb bitnami/mariadb -f helmvalues/local.yaml
    #     helm upgrade --install --create-namespace --namespace postgresql --wait --timeout 30m --version=10.13.14 postgresql bitnami/postgresql -f helmvalues/local.yaml
    #     helm upgrade --install --create-namespace --namespace mongodb --wait --timeout 30m --version=10.30.6 mongodb bitnami/mongodb -f helmvalues/local.yaml
    - name: Install Lagoon
      run: |
        helm upgrade --install --create-namespace --namespace lagoon --wait --timeout 30m lagoon-core lagoon-core-k8s-122/lagoon-core -f helmvalues/lagoon-core.yaml -f helmvalues/local.yaml
        helm upgrade --install --create-namespace --namespace lagoon --wait --timeout 30m lagoon-build-deploy lagoon-build-deploy-k8s-122/lagoon-build-deploy -f helmvalues/lagoon-build-deploy.yaml -f helmvalues/local.yaml
        helm upgrade --install --create-namespace --namespace lagoon --wait --timeout 30m lagoon-remote lagoon-remote-k8s-122/lagoon-remote -f helmvalues/lagoon-remote.yaml -f helmvalues/local.yaml
    - name: Update build-deploy-token in lagoon-test and install tests
      run: |
        kubectl -n lagoon get secret -o json | jq -r '.items[] | select(.metadata.name | match("lagoon-build-deploy-token")) | .data.token | @base64d' | xargs -I ARGS yq -i eval '.token = "ARGS"' helmvalues/local.yaml
        helm upgrade --install --create-namespace --namespace lagoon --wait --timeout 30m lagoon-test lagoon/lagoon-test -f helmvalues/lagoon-test.yaml -f helmvalues/local.yaml
    - name: Update build-deploy-token in lagoon-test and run tests
      run: |
        helm test lagoon-test --namespace lagoon --logs --timeout 15m
#        timeout 10m kubectl logs -f -l app.kubernetes.io/instance=lagoon-test -n lagoon
    - name: Test
      run: |
        kubectl cluster-info
        kubectl get pods -A
        kubectl get ingress -A